---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: uptime-kuma-httproute
  namespace: monitoring
spec:
  parentRefs:
  - name: traefik-gateway
    namespace: traefik
  hostnames: ["uptime.mbhlabs.uk"]
  rules:
  - backendRefs:
    - name: uptime-kuma-service
      port: 3001
